// <auto-generated />
using System;
using CurrencyTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurrencyTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528190909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurrencyTracker.Domain.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CurrentRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("current_rate");

                    b.Property<DateTimeOffset>("FiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fired_at");

                    b.Property<decimal>("ObservedChangePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("observed_change_percent");

                    b.Property<decimal>("PreviousRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("previous_rate");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_alerts_rule_id");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("CurrencyTracker.Domain.Alerts.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("threshold_percent");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_alert_rules_owner_id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("CurrencyTracker.Domain.Currencies.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NumericCode")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_code");

                    b.HasKey("Code")
                        .HasName("pk_currencies");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("CurrencyTracker.Domain.Rates.RateSnapshot", b =>
                {
                    b.Property<string>("Base")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("date")
                        .HasColumnName("as_of");

                    b.HasKey("Base", "AsOf")
                        .HasName("pk_rate_snapshots");

                    b.ToTable("rate_snapshots", (string)null);
                });

            modelBuilder.Entity("CurrencyTracker.Domain.Rates.RateSnapshot", b =>
                {
                    b.OwnsMany("CurrencyTracker.Domain.Rates.ExchangeRate", "Rates", b1 =>
                        {
                            b1.Property<string>("snapshot_base")
                                .HasColumnType("character varying(3)")
                                .HasColumnName("snapshot_base");

                            b1.Property<DateOnly>("snapshot_as_of")
                                .HasColumnType("date")
                                .HasColumnName("snapshot_as_of");

                            b1.Property<string>("Quote")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("quote");

                            b1.Property<DateOnly>("AsOf")
                                .HasColumnType("date")
                                .HasColumnName("as_of");

                            b1.Property<string>("Base")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("rate");

                            b1.HasKey("snapshot_base", "snapshot_as_of", "Quote")
                                .HasName("pk_exchange_rates");

                            b1.ToTable("exchange_rates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("snapshot_base", "snapshot_as_of")
                                .HasConstraintName("fk_exchange_rates_rate_snapshots_snapshot_base_snapshot_as_of");
                        });

                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
