name: _test-build (delete before merge)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-ubuntu:
    uses: ./.github/workflows/_reusable-build.yml
    with:
      os: ubuntu-latest
      configuration: Release

  call-windows:
    uses: ./.github/workflows/_reusable-build.yml
    with:
      os: windows-latest
      configuration: Release